
# I stuggled to compile ODE for plain C, so instead I'll compile my Raylib project using C++

main:
	# ODE motion demo with Raylib windowing, but not yet any rendering 
	g++ -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL -lraylib -lode demo_motion_raylib.cpp -std=c++11


